language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "blead"
sudo: false
matrix:
  fast_finish: true
  include:
    - perl: 5.26
      env: COVERAGE=1
  allow_failures:
    - perl: blead
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
branches:
  except:
    - /^wip\//
    - /^blocked/
    - /^issue\d+/
    - /^gh\d+/
